name: fabrik_cli
description: A CLI to generate scalable, testable, clean Flutter feature scaffolding using DDD layered architecture.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  mason: ^0.1.1
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

executables:
  fabrik: bin/main.dart
