targets:
  $default:
    builders:
      fabrik_model_generator:fabrik_model:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - test/**.dart

builders:
  fabrik_model:
    import: "package:fabrik_model_generator/fabrik_model_generator.dart"
    builder_factories: ["fabrikModelBuilder"]
    build_extensions: { ".dart": [".fmodel.dart"] }
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
