name: fabrik_model_generator
description: "A new Flutter package project."
version: 0.0.1
# homepage:
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  collection: ^1.18.0
  meta: ^1.9.1
  fabrik_model:
    path: ../fabrik_model
  flutter:
    sdk: flutter
  code_builder: ^4.10.0
  dart_style: ^2.3.4
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
