name: fabrik
description: >
  A CLI to generate scalable, testable, clean Flutter feature scaffolding using DDD layered architecture.

version: 0.1.7
homepage: https://fabriktool.com
repository: https://github.com/abhakhand/fabrik
issue_tracker: https://github.com/abhakhand/fabrik/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  fabrik:

dependencies:
  args: ^2.7.0
  mason: ^0.1.1
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

include:
  - lib/src/bricks/feature.bundle
