name: fabrik_snackbar
description: "Beautifully crafted Snackbar + Toast package from the Fabrik Toolkit. Easy to use, highly customizable, works on all platforms."
version: 0.1.2
homepage: https://fabriktool.com
repository: https://github.com/abhakhand/fabrik/tree/feat/fabrik_snackbar/packages/fabrik_snackbar

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
