name: fabrik_result
description: "A lightweight toolkit for functional-style types like Either, built for clarity and real-world use."
version: 0.1.0
homepage: https://fabriktool.com
repository: https://github.com/abhakhand/fabrik/tree/feat/fabrik_result/packages/fabrik_result

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
